filebeat.inputs:
  - type: filestream
    id: spring-boot-logs
    enabled: true
    paths:
      - /logs/spring-boot-app*.log

    # JSON + multiline (stacktrace) için:
    # 1) önce multiline ile JSON bloklarını birleştir
    # 2) sonra ndjson parser ile JSON'u parse et
    parsers:
      - multiline:
          pattern: '^{'
          negate: true
          match: after
      - ndjson:
          target: "log"              # JSON alanları log.* altında toplansın
          add_error_key: true
          message_key: "message"     # JSON içindeki "message" alanını event.message'a taşır

processors:
  # logback-spring.xml'deki timestamp: yyyy-MM-dd'T'HH:mm:ss.SSS'Z' (UTC)
  # örn: 2025-12-13T09:12:34.123Z
  - timestamp:
      field: "log.@timestamp"
      layouts:
        - "2006-01-02T15:04:05.000Z"
      timezone: "UTC"
      ignore_failure: true

  # İstersen burada env/service gibi etiketleri köke koy (Kibana filtreleri kolaylaşır)
  - add_fields:
      target: ""
      fields:
        env: "local"
        service: "monitoring-app"

  - add_host_metadata: ~
  - add_docker_metadata: ~

# Output -> Logstash (TLS)
output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: true
  ssl.certificate_authorities:
    - "/usr/share/filebeat/config/certs/ca/ca.crt"
  ssl.certificate: "/usr/share/filebeat/config/certs/filebeat/filebeat.crt"
  ssl.key: "/usr/share/filebeat/config/certs/filebeat/filebeat.key"
  ssl.verification_mode: certificate

# Filebeat kendi index/template yönetmesin (Logstash/ES tarafında yöneteceğiz)
setup.ilm.enabled: false
setup.template.enabled: false

# Registry (kaldığı yerden devam)
filebeat.registry.path: /usr/share/filebeat/data/registry

logging.level: info
